version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "7860:7860"
    volumes:
      # Mount backend for live reloading with nodemon
      - ./backend:/app
      # Anonymous volume for node_modules
      - /app/node_modules
    env_file:
      - ./backend/.env
    # The command `npm run dev` is run from the WORKDIR /app
    command: npm run dev
