name: Create or Update createSuperAdmin.js

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/create-superadmin-script.yml'

permissions:
  contents: write

jobs:
  create-superadmin-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create scripts folder and createSuperAdmin.js
        run: |
          mkdir -p scripts
          cat > scripts/createSuperAdmin.js <<'EOF'
          const mongoose = require('mongoose');
          const bcrypt = require('bcryptjs');

          const userSchema = new mongoose.Schema({
            name: String,
            email: { type: String, unique: true },
            password: String,
            role: String,
            isProfileVisible: Boolean
          }, { collection: 'users' });

          const User = mongoose.model('User', userSchema);

          async function createSuperAdmin() {
            await mongoose.connect(process.env.MONGO_URI);

            const email = 'enadoctemp@gmail.com';
            const password = 'Abc@1234';
            const hashedPassword = await bcrypt.hash(password, 10);

            const exists = await User.findOne({ email, role: 'superadmin' });
            if (exists) {
              console.log('Superadmin already exists.');
              await mongoose.disconnect();
              return;
            }

            const superadmin = new User({
              name: 'Super Admin',
              email,
              password: hashedPassword,
              role: 'superadmin',
              isProfileVisible: true
            });

            await superadmin.save();
            console.log('Superadmin created successfully!');
            await mongoose.disconnect();
          }

          createSuperAdmin().catch(err => {
            console.error(err);
            mongoose.disconnect();
          });
          EOF

      - name: Commit and push createSuperAdmin.js
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git add scripts/createSuperAdmin.js
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: add or update scripts/createSuperAdmin.js"
            git push
          fi

      - name: Print files in scripts directory
        run: |
          echo "Files in scripts directory:"
          find scripts -type f
