name: Scan for Missing NPM Packages in Backend

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**/*.js'
      - 'backend/**/*.ts'
      - 'backend/package.json'
      - 'backend/package-lock.json'

jobs:
  depcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install depcheck and jq
        run: |
          npm install -g depcheck
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run depcheck and save output
        run: depcheck --json > depcheck-output.json

      - name: Print depcheck-output.json to console
        run: cat depcheck-output.json

      - name: Print missing dependencies (if any) and fail if present
        run: |
          MISSING=$(jq -r '.missing | keys | @sh' depcheck-output.json)
          if [ "$MISSING" != "" ]; then
            echo "❌ Missing dependencies:"
            jq -r '.missing | to_entries[] | .key' depcheck-output.json
            exit 1
          else
            echo "✅ No missing dependencies!"
          fi
