name: Scan for Missing NPM Packages

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - 'package.json'
      - 'package-lock.json'

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install depcheck and jq
        run: |
          npm install -g depcheck
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run depcheck and save output
        run: depcheck --json > depcheck-output.json

      - name: Print depcheck-output.json to console
        run: cat depcheck-output.json

      - name: Fail if there are missing dependencies
        run: |
          MISSING=$(jq '.missing | length' depcheck-output.json)
          if [ "$MISSING" -gt 0 ]; then
            echo "❌ There are missing dependencies!"
            exit 1
          else
            echo "✅ No missing dependencies!"
          fi

      - name: Upload depcheck output as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: depcheck-output
          path: depcheck-output.json
